#![cfg_attr(feature = "fail-on-warnings", deny(warnings))]
#![warn(clippy::all, clippy::pedantic, clippy::nursery, clippy::cargo)]
#![allow(clippy::multiple_crate_versions)]

//! Shared session models for bcode.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fmt::{Display, Formatter};
use std::str::FromStr;
use uuid::Uuid;

/// Current persisted session event schema version.
pub const CURRENT_SESSION_EVENT_SCHEMA_VERSION: u16 = 8;

/// Unique session identifier.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SessionId(pub Uuid);

impl SessionId {
    /// Generate a new random session identifier.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }
}

impl Default for SessionId {
    fn default() -> Self {
        Self::new()
    }
}

impl Display for SessionId {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        Display::fmt(&self.0, f)
    }
}

impl FromStr for SessionId {
    type Err = uuid::Error;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Uuid::parse_str(value).map(Self)
    }
}

/// Unique connected-client identifier.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ClientId(pub Uuid);

impl ClientId {
    /// Generate a new random client identifier.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }
}

impl Default for ClientId {
    fn default() -> Self {
        Self::new()
    }
}

impl Display for ClientId {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        Display::fmt(&self.0, f)
    }
}

/// Session summary used by list/select flows.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionSummary {
    pub id: SessionId,
    pub name: Option<String>,
    pub client_count: usize,
}

/// Direction for paged session history reads.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SessionHistoryDirection {
    Forward,
    Backward,
}

/// Cursor for paged session history reads.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionHistoryCursor {
    pub sequence: u64,
}

/// Query for a bounded page of session history.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionHistoryQuery {
    #[serde(default)]
    pub cursor: Option<SessionHistoryCursor>,
    pub limit: usize,
    pub direction: SessionHistoryDirection,
}

/// Bounded page of replayable session history.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionHistoryPage {
    pub session_id: SessionId,
    pub events: Vec<SessionEvent>,
    #[serde(default)]
    pub next_cursor: Option<SessionHistoryCursor>,
    pub has_more: bool,
}

/// Replayable event emitted by a session.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionEvent {
    pub schema_version: u16,
    pub sequence: u64,
    pub session_id: SessionId,
    pub kind: SessionEventKind,
}

/// Model turn terminal outcome.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ModelTurnOutcome {
    Completed,
    Cancelled,
    Error,
    IdleTimeout,
    ToolRoundLimitReached,
    ProviderUnavailable,
}

/// Provider-neutral token usage persisted with a session.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionTokenUsage {
    /// Tokens supplied to the model for this turn or provider round.
    #[serde(default)]
    pub input_tokens: Option<u32>,
    /// Tokens generated by the model for this turn or provider round.
    #[serde(default)]
    pub output_tokens: Option<u32>,
    /// Provider-reported total tokens, when available.
    #[serde(default)]
    pub total_tokens: Option<u32>,
    /// Input tokens served from a provider cache, when available.
    #[serde(default)]
    pub cached_input_tokens: Option<u32>,
    /// Input tokens written to a provider prompt cache, when available.
    #[serde(default)]
    pub cache_write_input_tokens: Option<u32>,
    /// Reasoning tokens reported separately by a provider, when available.
    #[serde(default)]
    pub reasoning_tokens: Option<u32>,
}

impl SessionTokenUsage {
    /// Return the most reliable total token count for spend/session metering.
    #[must_use]
    pub fn metered_total_tokens(&self) -> Option<u32> {
        self.total_tokens.or_else(|| {
            let input = self.input_tokens.unwrap_or_default();
            let output = self.output_tokens.unwrap_or_default();
            (self.input_tokens.is_some() || self.output_tokens.is_some())
                .then_some(input.saturating_add(output))
        })
    }

    /// Return the token count that best represents current context pressure.
    #[must_use]
    pub const fn context_input_tokens(&self) -> Option<u32> {
        self.input_tokens
    }

    /// Return uncached input tokens when both input and cached counts are known.
    #[must_use]
    pub const fn uncached_input_tokens(&self) -> Option<u32> {
        match (self.input_tokens, self.cached_input_tokens) {
            (Some(input), Some(cached)) => Some(input.saturating_sub(cached)),
            _ => self.input_tokens,
        }
    }
}

/// Fine-grained diagnostic event persisted for session post-mortems.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionTraceEvent {
    /// Milliseconds since the Unix epoch when this trace event was recorded.
    pub timestamp_ms: u64,
    /// Optional model turn associated with this trace event.
    #[serde(default)]
    pub turn_id: Option<String>,
    /// Diagnostic phase.
    pub phase: SessionTracePhase,
    /// Structured diagnostic payload.
    pub payload: SessionTracePayload,
}

/// Diagnostic phase for a [`SessionTraceEvent`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SessionTracePhase {
    ModelRequestBuilt,
    ModelProviderRoundStarted,
    ModelProviderRoundFinished,
    ModelProviderEvent,
    ToolInvocationStarted,
    ToolPolicyEvaluated,
    ToolPermissionWaitStarted,
    ToolPermissionWaitFinished,
    ToolInvocationFinished,
    ContextCompactionSkipped,
    ContextCompactionStarted,
    ContextCompactionFinished,
}

/// Structured diagnostic payload for a [`SessionTraceEvent`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SessionTracePayload {
    ModelRequestBuilt {
        provider: String,
        model: String,
        agent_id: String,
        message_count: usize,
        tool_count: usize,
        system_prompt_chars: usize,
        prompt_cache_mode: String,
        conversation_reuse_mode: String,
        uses_previous_provider_response: bool,
        metadata: BTreeMap<String, String>,
        request: Option<TraceBlobRef>,
    },
    ProviderRound {
        provider_turn_id: Option<String>,
        provider: String,
        round: Option<u32>,
        stop_reason: Option<String>,
        duration_ms: Option<u64>,
        error: Option<String>,
    },
    ProviderEvent {
        event_type: String,
        detail: Option<String>,
    },
    ToolInvocationStarted {
        tool_call_id: String,
        plugin_id: String,
        tool_name: String,
        side_effect: String,
        requires_permission: bool,
        arguments: Option<TraceBlobRef>,
    },
    ToolPolicyEvaluated {
        tool_call_id: String,
        agent_id: String,
        decision: String,
        reason: Option<String>,
    },
    ToolPermissionWait {
        permission_id: String,
        tool_call_id: String,
        approved: Option<bool>,
        duration_ms: Option<u64>,
    },
    ToolInvocationFinished {
        tool_call_id: String,
        duration_ms: u64,
        is_error: bool,
        output_bytes: usize,
        output: Option<TraceBlobRef>,
    },
    ContextCompaction {
        reason: String,
        projected_context_chars: usize,
        compacted: bool,
        message: Option<String>,
    },
}

/// Reference to a trace payload stored outside the main session event stream.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TraceBlobRef {
    pub sha256: String,
    pub path: String,
    pub content_type: String,
    pub byte_len: u64,
    pub redaction: TraceRedaction,
}

/// Redaction status for a trace blob.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TraceRedaction {
    None,
    Automatic,
    ManualRequired,
}

/// Session event payload.
///
/// IMPORTANT: This enum is persisted with `bmux_codec`, whose binary enum
/// representation is order-sensitive. Do not reorder existing variants or
/// insert new variants between existing ones. Add new variants only at the end,
/// and bump `CURRENT_SESSION_EVENT_SCHEMA_VERSION` when doing so.
///
/// Reordering variants can make existing persisted `*.events` session files
/// decode as the wrong event type or fail daemon startup.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SessionEventKind {
    SessionCreated {
        name: Option<String>,
    },
    ClientAttached {
        client_id: ClientId,
    },
    ClientDetached {
        client_id: ClientId,
    },
    UserMessage {
        client_id: ClientId,
        text: String,
    },
    AssistantDelta {
        text: String,
    },
    AssistantMessage {
        text: String,
    },
    ToolCallRequested {
        tool_call_id: String,
        tool_name: String,
        arguments_json: String,
    },
    ToolCallFinished {
        tool_call_id: String,
        result: String,
        #[serde(default)]
        is_error: bool,
    },
    PermissionRequested {
        permission_id: String,
        tool_call_id: String,
        tool_name: String,
        arguments_json: String,
    },
    PermissionResolved {
        permission_id: String,
        approved: bool,
    },
    ModelChanged {
        provider: String,
        model: String,
    },
    SystemMessage {
        text: String,
    },
    AgentChanged {
        agent_id: String,
    },
    ModelTurnStarted {
        turn_id: String,
    },
    ModelTurnFinished {
        turn_id: String,
        outcome: ModelTurnOutcome,
        #[serde(default)]
        message: Option<String>,
    },
    ModelUsage {
        turn_id: String,
        usage: SessionTokenUsage,
    },
    ContextCompacted {
        summary: String,
        compacted_through_sequence: u64,
    },
    SessionRenamed {
        name: Option<String>,
    },
    TraceEvent {
        trace: Box<SessionTraceEvent>,
    },
}
