id      = "example.hello"
name    = "Hello Example Plugin"
version = "0.0.1"

[[services]]
description  = "Echo service used by smoke tests"
interface_id = "example-hello/v1"
name         = "Hello Echo"

[[event_subscriptions]]
topic = "example.event"

[[event_subscriptions]]
topic = "bcode.session.event"

[runtime]
abi_version  = 2
event_symbol = "bcode_plugin_handle_event_v1"
library      = "libbcode_hello_plugin.dylib"
type         = "native"
